# api redirect.
[[redirects]]
  from = "/proxy/*"
  to = "https://loffle.cf/:splat"
  status = 200
  force = true

# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200